#!/bin/sh
# TODO: kbuildsycoca automation (actually working)
# TODO: fix supergfxctl hybrid mode causing chromium applications to freak out
# TODO: keybind to send all views in a tag to another tag
# TODO: sigterm to all applications when shutting down

riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
riverctl background-color 0xd8dee9
riverctl xcursor-theme Nordzy-cursors 29

# Application shortcuts
riverctl map normal Super W spawn $TERMINAL
riverctl map normal Super A spawn $BROWSER
riverctl map normal Super E spawn dolphin
riverctl map normal None Print spawn "quickshot -i -p | wl-copy"
riverctl map normal Super+Shift O spawn normcap
riverctl map normal Super V spawn "cliphist list | fuzzel --dmenu | cliphist decode | wl-copy"
riverctl map normal Super+Shift V spawn nwg-clipman
riverctl map normal Super C spawn "wl-color-picker clipboard"
riverctl map normal Super Period spawn smile
riverctl map normal None F11 toggle-fullscreen

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to exit river
riverctl map normal Super D spawn wlogout

riverctl map normal Super R spawn fuzzel

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super H focus-view left
riverctl map normal Super L focus-view right
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift L swap right
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
# riverctl map normal Super+Shift J swap next
# riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
# riverctl map normal Super Period focus-output next
# riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
# riverctl map normal Super+Shift Period send-to-output next
# riverctl map normal Super+Shift Comma send-to-output previous
#
# Super+Return to bump the focused view to the top of the layout stack
# riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivercarro(1)
# riverctl map normal Super H send-layout-cmd rivercarro "main-ratio -0.05"
# riverctl map normal Super L send-layout-cmd rivercarro "main-ratio +0.05"

# Super+Alt+J and Super+Alt+K to increment/decrement the main count of rivercarro(1)
riverctl map normal Super+Alt J send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super+Alt K send-layout-cmd rivercarro "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Control H move left 100
riverctl map normal Super+Control J move down 100
riverctl map normal Super+Control K move up 100
riverctl map normal Super+Control L move right 100

# Super+Alt+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Shift+Alt H resize horizontal -100
riverctl map normal Super+Shift+Alt J resize vertical 100
riverctl map normal Super+Shift+Alt K resize vertical -100
riverctl map normal Super+Shift+Alt L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+F to toggle float
riverctl map normal Super F toggle-float

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivercarro "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set keyboard repeat rate
riverctl set-repeat 75 200

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

riverctl rule-add ssd

# Set the default layout generator to be rivercarro and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
rivercarro -per-tag -inner-gaps 3 -outer-gaps 5 -main-ratio 0.5 -main-location right &
riverctl map normal Super B send-layout-cmd rivercarro "main-location-cycle right,monocle"
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad natural-scroll enabled
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad scroll-factor 0.2
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad accel-profile flat
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad drag enabled
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad middle-emulation enabled
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad pointer-accel 0.2
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad tap-button-map left-right-middle
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad tap enabled
riverctl input pointer-1739-52981-SYNA2BA6:00_06CB:CEF5_Touchpad scroll-method two-finger
riverctl input pointer-5426-156-Razer_Razer_DeathAdder_V2_X_HyperSpeed_Mouse natural-scroll enabled
riverctl input pointer-5426-156-Razer_Razer_DeathAdder_V2_X_HyperSpeed_Mouse scroll-factor 0.1
riverctl input pointer-5426-156-Razer_Razer_DeathAdder_V2_X_HyperSpeed_Mouse accel-profile none
riverctl input pointer-5426-156-Razer_Razer_DeathAdder_V2_X_HyperSpeed_Mouse pointer-accel -1.0
riverctl hide-cursor 10000
riverctl hide-cursor when-typing enabled
riverctl border-width 1
riverctl border-color-focused 0xa3be8c
riverctl border-color-unfocused 0x5e81ac
riverctl border-color-urgent 0xebcb8b

# Scale displays
wlr-randr --output eDP-2 --scale 2
wlr-randr --output eDP-1 --scale 2

# Set up scratchpad
thunderbird_tag=$((1 << 20 ))
scratch_tag=$((1 << 21))

riverctl map normal Super M toggle-focused-tags ${scratch_tag}		# toggle the scratchpad
riverctl map normal Super+Shift M set-view-tags ${scratch_tag}		# send windows to the scratchpad

# Set spawn tagmask to ensure new windows do not have the scratchpad tag unless explicitly set.
all_but_thunderbird=$(( ((1 << 32) - 1) ^ $thunderbird_tag ))
riverctl spawn-tagmask ${all_but_thunderbird}

riverctl spawn "wbg ~/Pictures/bg.jpg"
riverctl spawn nm-applet
riverctl spawn blueman-applet
riverctl spawn mako
# riverctl spawn waybar
waybar > ~/.waybar-log &
riverctl spawn "wl-paste --type text --watch cliphist store"
riverctl spawn "wl-paste --type image --watch cliphist store"
riverctl spawn "discord --start-minimized --enable-features=VaapiVideoDecode,UseOzonePlatform --ozone-platform=wayland"
riverctl spawn "swayidle -w \
    timeout 300 'brightnessctl get > ~/.prev_brightness; brightnessctl set 0' \
    resume 'brightnessctl set \`cat ~/.prev_brightness\` && rm ~/.prev_brightness' \
    timeout 600 'sleep 1 && ~/scripts/lock.sh' \
    timeout 900 ~/.config/river/scripts/dynamic-sleep.sh \
    before-sleep ~/scripts/lock.sh"
kbuildsycoca6
kbuildsycoca5
rclone sync /home/sabari/Sabari/Education/SNU/ gdrive:SNU
riverctl spawn thunderbird
riverctl rule-add -app-id thunderbird tags ${thunderbird_tag} 
riverctl rule-add -title Smile float
riverctl rule-add -title Calculator float
riverctl spawn "brightnessctl set 320"
