[env]
term = "xterm-256color"

# Colors (Nord)
[colors]
cursor = { text = "CellBackground", cursor = "#81A1C1" }

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black = '#3B4252'
red = '#BF616A'
green = '#A3BE8C'
yellow = '#EBCB8B'
blue = '#81A1C1'
magenta = '#B48EAD'
cyan = '#88C0D0'
white = '#E5E9F0'

# Bright colors
[colors.bright]
black = '#4C566A'
red = '#BF616A'
green = '#A3BE8C'
yellow = '#EBCB8B'
blue = '#81A1C1'
magenta = '#B48EAD'
cyan = '#8FBCBB'
white = '#ECEFF4'

[window]
padding.x = 2
padding.y = 3
dynamic_padding = true

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"
size = 10.5
offset.x = -1
offset.y = -1

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[bell]
# animation = "EaseOut"
# color = "#8FBCBB"
duration = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 10
